[package]
name = "peregrine"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3" }
bevy_common_assets = { version = "0.14.0", features = ["ron"] }
fixed = { version = "1.29.0", features = ["serde"] }
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
